#include "..\stdafx.h"

MANID ManID[] = {
{1,     "Microsoft Corporation"},
{2,     "Creative Labs, Inc."},
{3,     "Media Vision, Inc."},
{4,     "Fujitsu Corp."},
{5,     "PRAGMATRAX Software"},
{6,     "Cyrix Corporation"},
{7,     "Philips Speech Processing"},
{8,     "NetXL, Inc."},
{9,     "ZyXEL Communications, Inc."},
{10,    "BeCubed Software Inc."},
{11,    "Aardvark Computer Systems, Inc."},
{12,    "Bin Tec Communications GmbH"},
{13,    "Hewlett-Packard Company"},
{14,    "Aculab plc"},
{15,    "Faith,Inc."},
{16,    "Mitel Corporation"},
{17,    "Quantum3D, Inc."},
{18,    "Siemens-Nixdorf"},
{19,    "E-mu Systems, Inc."},
{20,    "Artisoft, Inc."},
{21,    "Turtle Beach, Inc."},
{22,    "IBM Corporation"},
{23,    "Vocaltec Ltd."},
{24,    "Roland"},
{25,    "DSP Solutions, Inc."},
{26,    "NEC"},
{27,    "ATI Technologies Inc."},
{28,    "Wang Laboratories, Inc."},
{29,    "Tandy Corporation"},
{30,    "Voyetra"},
{31,    "Antex Electronics Corporation"},
{32,    "ICL Personal Systems"},
{33,    "Intel Corporation"},
{34,    "Advanced Gravis"},
{35,    "Video Associates Labs, Inc."},
{36,    "InterActive Inc."},
{37,    "Yamaha Corporation of America"},
{38,    "Everex Systems, Inc."},
{39,    "Echo Speech Corporation"},
{40,    "Sierra Semiconductor Corp"},
{41,    "Computer Aided Technologies"},
{42,    "APPS Software International"},
{43,    "DSP Group, Inc."},
{44,    "microEngineering Labs"},
{45,    "Computer Friends, Inc."},
{46,    "ESS Technology"},
{47,    "Audio, Inc."},
{48,    "Motorola, Inc."},
{49,    "Canopus, co., Ltd."},
{50,    "Seiko Epson Corporation"},
{51,    "Truevision"},
{52,    "Aztech Labs, Inc."},
{53,    "Videologic"},
{54,    "SCALACS"},
{55,    "Korg Inc."},
{56,    "Audio Processing Technology"},
{57,    "Integrated Circuit Systems, Inc."},
{58,    "Iterated Systems, Inc."},
{59,    "Metheus"},
{60,    "Logitech, Inc."},
{61,    "Winnov, Inc."},
{62,    "NCR Corporation"},
{63,    "EXAN"},
{64,    "AST Research Inc."},
{65,    "Willow Pond Corporation"},
{66,    "Sonic Foundry"},
{67,    "Vitec Multimedia"},
{68,    "MOSCOM Corporation"},
{69,    "Silicon Soft, Inc."},
{70,    "TerraTec Electronic GmbH"},
{71,    "MediaSonic Ltd."},
{72,    "SANYO Electric Co., Ltd."},
{73,    "Supermac"},
{74,    "Audio Processing Technology"},
{75,    "NOGATECH Ltd."},
{76,    "Speech Compression"},
{77,    "Ahead, Inc."},
{78,    "Dolby Laboratories"},
{79,    "OKI"},
{80,    "AuraVision Corporation"},
{81,    "Ing C. Olivetti & C., S.p.A."},
{82,    "I/O Magic Corporation"},
{83,    "Matsushita Electric Industrial Co., Ltd."},
{84,    "Control Resources Limited"},
{85,    "Xebec Multimedia Solutions Limited"},
{86,    "New Media Corporation"},
{87,    "Natural MicroSystems"},
{88,    "Lyrrus Inc."},
{89,    "Compusic"},
{90,    "OPTi Computers Inc."},
{91,    "Adlib Accessories Inc."},
{92,    "Compaq Computer Corp."},
{93,    "Dialogic Corporation"},
{94,    "InSoft, Inc."},
{95,    "M.P. Technologies, Inc."},
{96,    "Weitek"},
{97,    "Lernout & Hauspie"},
{98,    "Quanta Computer Inc."},
{99,    "Apple Computer, Inc."},
{100,   "Digital Equipment Corporation"},
{101,   "Mark of the Unicorn"},
{102,   "Workbit Corporation"},
{103,   "Ositech Communications Inc."},
{104,   "miro Computer Products AG"},
{105,   "Cirrus Logic"},
{106,   "ISOLUTION  B.V."},
{107,   "Horizons Technology, Inc."},
{108,   "Computer Concepts Ltd."},
{109,   "Voice Technologies Group, Inc."},
{110,   "Radius"},
{111,   "Rockwell International"},
{112,   "Co. XYZ for testing"},
{113,   "Opcode Systems"},
{114,   "Voxware Inc."},
{115,   "Northern Telecom Limited"},
{116,   "APICOM"},
{117,   "Grande Software"},
{118,   "ADDX"},
{119,   "Wildcat Canyon Software"},
{120,   "Rhetorex Inc."},
{121,   "Brooktree Corporation"},
{125,   "ENSONIQ Corporation"},
{126,   "FAST Multimedia AG"},
{127,   "nVidia Corporation"},
{128,   "OKSORI Co., Ltd."},
{129,   "DiAcoustics, Inc."},
{130,   "Gulbransen, Inc."},
{131,   "Kay Elemetrics, Inc."},
{132,   "Crystal Semiconductor Corporation"},
{133,   "Splash Studios"},
{134,   "Quarterdeck Corporation"},
{135,   "TDK Corporation"},
{136,   "Digital Audio Labs, Inc."},
{137,   "Seer Systems, Inc."},
{138,   "PictureTel Corporation"},
{139,   "AT&T Microelectronics"},
{140,   "Osprey Technologies, Inc."},
{141,   "Mediatrix Peripherals"},
{142,   "SounDesignS M.C.S. Ltd."},
{143,   "A.L. Digital Ltd."},
{144,   "Spectrum Signal Processing, Inc."},
{145,   "Electronic Courseware Systems, Inc."},
{146,   "AMD"},
{147,   "Core Dynamics"},
{148,   "CANAM Computers"},
{149,   "Softsound, Ltd."},
{150,   "Norris Communications, Inc."},
{151,   "Danka Data Devices"},
{152,   "EuPhonics"},
{153,   "Precept Software, Inc."},
{154,   "Crystal Net Corporation"},
{155,   "Chromatic Research, Inc."},
{156,   "Voice Information Systems, Inc."},
{157,   "Vienna Systems"},
{158,   "Connectix Corporation"},
{159,   "Gadget Labs LLC"},
{160,   "Frontier Design Group LLC"},
{161,   "Viona Development GmbH"},
{162,   "Casio Computer Co., LTD"},
{163,   "Diamond Multimedia"},
{164,   "S3"},
{165,   "D-Vision Systems, Inc."},
{166,   "Netscape Communications"},
{167,   "Soundspace Audio"},
{168,   "VanKoevering Company"},
{169,   "Q-Team"},
{170,   "Zefiro Acoustics"},
{171,   "Studer Professional Audio AG"},
{172,   "Fraunhofer IIS"},
{173,   "Quicknet Technologies"},
{174,   "Alaris, Inc."},
{175,   "SIC Resource Inc."},
{176,   "NeoMagic Corporation"},
{177,   "Merging Technologies S.A."},
{178,   "Xirlink, Inc."},
{179,   "Colorgraph (UK) Ltd"},
{180,   "Oak Technology, Inc."},
{181,   "Aureal Semiconductor"},
{182,   "Vivo Software"},
{183,   "Sharp"},
{184,   "Lucent Technologies"},
{185,   "AT&T Labs, Inc."},
{186,   "Sun Communications, Inc."},
{187,   "Sorenson Vision"},
{188,   "InVision Interactive"},
{189,   "Deutsche Telekom Berkom GmbH"},
{190,   "Marian GbR Leipzig"},
{191,   "Digital Processing Systems, Inc."},
{192,   "BCB Holdings Inc."},
{193,   "Motion Pixels"},
{194,   "QDesign Corporation"},
{195,   "Nokia Mobile Phones"},
{196,   "DataFusion Systems (Pty) (Ltd)"},
{197,   "The Duck Corporation"},
{198,   "Future Technology Resources Pty Ltd"},
{199,   "BERCOS GmbH"},
{200,   "OnLive! Technologies, Inc."},
{201,   "Siemens Business Communications Systems"},
{202,   "TeraLogic, Inc."},
{203,   "PhoNet Communications Ltd."},
{204,   "Winbond Electronics Corp"},
{205,   "Virtual Music, Inc."},
{206,   "e-Net, Inc."},
{207,   "Guillemot International"},
{208,   "Emagic Soft- und Hardware GmbH"},
{209,   "MWM Acoustics LLC"},
{210,   "Pacific Research and Engineering Corporation"},
{211,   "Sipro Lab Telecom Inc."},
{212,   "Lynx Studio Technology, Inc."},
{213,   "Spectrum Productions"},
{214,   "Dictaphone Corporation"},
{215,   "QUALCOMM, Inc."},
{216,   "Ring Zero Systems, Inc"},
{217,   "AudioScience Inc."},
{218,   "Pinnacle Systems, Inc."},
{219,   "EES Technik für Musik GmbH"},
{220,   "haftmann#software"},
{221,   "Lucid Technology, Symetrix Inc."},
{222,   "Headspace, Inc"},
{223,   "UNISYS CORPORATION"},
{224,   "Luminositi, Inc."},
{225,   "ACTIVE VOICE CORPORATION"},
{226,   "Digital Theater Systems, Inc."},
{227,   "DIGIGRAM"},
{228,   "Softlab-Nsk"},
{229,   "ForteMedia, Inc"},
{230,   "Sonorus, Inc."},
{231,   "Array Microsystems, Inc."},
{232,   "Data Translation, Inc."},
{233,   "I-link Worldwide"},
{234,   "Selsius Systems Inc."},
{235,   "AdMOS Technology, Inc."},
{236,   "Lexicon Inc."},
{237,   "Silicon Graphics Inc."},
{238,   "Interactive Product Inc."},
{239,   "IC Ensemble, Inc."},
{240,   "ViewQuest Technologies Inc."},
{241,   "eTEK Labs Inc."},
{242,   "Consistent Software"},
{243,   "Alesis Studio Electronics"},
{244,   "INTERNET Corporation"},
{245,   "Sony Corporation"},
{246,   "Hyperactive Audio Systems, Inc."},
{247,   "UHER informatic GmbH"},
{248,   "Sydec NV"},
{249,   "Flexion Systems Ltd."},
{250,   "Via Technologies, Inc."},
{251,   "Micronas Semiconductors, Inc."},
{252,   "Analog Devices, Inc."},
{253,   "Hewlett Packard Company"},
{254,   "Matrox"},
{255,   "Quick Audio, GbR"},
{256,   "You/Com Audiocommunicatie BV"},
{257,   "Richmond Sound Design Ltd."},
{258,   "I-O Data Device, Inc."},
{259,   "ICCC A/S"},
{260,   "3COM Corporation"},
{261,   "Malden Electronics Ltd."},
{262,   "3Dfx Interactive, Inc."},
{263,   "Mindmaker, Inc."},
{264,   "Telekol Corp."},
{265,   "ST Microelectronics"},
{266,   "Algo Vision Systems GmbH"}};


PRODUCTID ProdID[] = {
// Microsoft
{1,1       ,"Midi Mapper"},
{1,2       ,"Wave Mapper"},
{1,3       ,"Sound Blaster MIDI output port"},
{1,4       ,"Sound Blaster MIDI input port"},
{1,5       ,"Sound Blaster internal synth"},
{1,6       ,"Sound Blaster waveform output"},
{1,7       ,"Sound Blaster waveform input"},
{1,9       ,"Ad Lib Compatible synth"},
{1,10      ,"MPU 401 compatible MIDI output port"},
{1,11      ,"MPU 401 compatible MIDI input port"},
{1,12      ,"Joystick adapter"},
{1,13      ,"PC speaker waveform output"},
{1,14      ,"MS Audio Board waveform input"},
{1,15      ,"MS Audio Board waveform output"},
{1,16      ,"MS Audio Board  Stereo FM synth"},
{1,17      ,"MS Audio Board Mixer Driver"},
{1,18      ,"MS OEM Audio Board waveform input"},
{1,19      ,"MS OEM Audio Board waveform output"},
{1,20      ,"MS OEM Audio Board Stereo FM Synth"},
{1,21      ,"MS Audio Board Aux. Port"},
{1,22      ,"MS OEM Audio Aux Port"},
{1,23      ,"MS Vanilla driver waveform input"},
{1,24      ,"MS Vanilla driver wavefrom output"},
{1,25      ,"MS Vanilla driver MIDI in"},
{1,26      ,"MS Vanilla driver MIDI  external out"},
{1,27      ,"MS Vanilla driver MIDI synthesizer"},
{1,28      ,"MS Vanilla driver aux (line in)"},
{1,29      ,"MS Vanilla driver aux (mic)"},
{1,30      ,"MS Vanilla driver aux (CD)"},
{1,31      ,"MS OEM Audio Board Mixer Driver"},
{1,32      ,"MS Audio Compression Manager"},
{1,33      ,"MS ADPCM Codec"},
{1,34      ,"IMA ADPCM Codec"},
{1,35      ,"MS Filter"},
{1,36      ,"GSM 610 codec"},
{1,37      ,"G.711 codec"},
{1,38      ,"PCM converter"},
{1,39      ,"Sound Blaster 16 waveform input"},
{1,40      ,"Sound Blaster 16  waveform output"},
{1,41      ,"Sound Blaster 16 midi-in"},
{1,42      ,"Sound Blaster 16 midi out"},
{1,43      ,"Sound Blaster 16 FM Synthesis"},
{1,44      ,"Sound Blaster 16 aux (line in)"},
{1,45      ,"Sound Blaster 16 aux (CD)"},
{1,46      ,"Sound Blaster 16 mixer device"},
{1,47      ,"Sound Blaster Pro waveform input"},
{1,48      ,"Sound Blaster Pro waveform output"},
{1,49      ,"Sound Blaster Pro midi in"},
{1,50      ,"Sound Blaster Pro midi out"},
{1,51      ,"Sound Blaster Pro FM synthesis"},
{1,52      ,"Sound Blaster Pro aux (line in )"},
{1,53      ,"Sound Blaster Pro aux (CD)"},
{1,54      ,"Sound Blaster Pro mixer"},
{1,55      ,"WSS NT wave in"},
{1,56      ,"WSS NT wave out"},
{1,57      ,"WSS NT FM synth"},
{1,58      ,"WSS NT mixer"},
{1,59      ,"WSS NT aux"},
{1,60      ,"Sound Blaster 16 waveform input"},
{1,61      ,"Sound Blaster 16 waveform output"},
{1,62      ,"Sound Blaster 16 midi-in"},
{1,63      ,"Sound Blaster 16 midi out"},
{1,64      ,"Sound Blaster 16 FM Synthesis"},
{1,65      ,"Sound Blaster 16 aux (line in)"},
{1,66      ,"Sound Blaster 16 aux (CD)"},
{1,67      ,"Sound Blaster 16 mixer device"},
{1,68      ,"Sound Blaster Pro waveform input"},
{1,69      ,"Sound Blaster Pro waveform output"},
{1,70      ,"Sound Blaster Pro midi in"},
{1,71      ,"Sound Blaster Pro midi out"},
{1,72      ,"Sound Blaster Pro FM synthesis"},
{1,73      ,"Sound Blaster Pro aux (line in)"},
{1,74      ,"Sound Blaster Pro aux (CD)"},
{1,75      ,"Sound Blaster Pro mixer"},
{1,76      ,"Yamaha OPL2/OPL3 compatible FM synthesis"},
{1,80      ,"Voice Modem Serial Line Wave Input"},
{1,81      ,"Voice Modem Serial Line Wave Output"},
{1,82      ,"Voice Modem Serial Handset Wave Input"},
{1,83      ,"Voice Modem Serial Handset Wave Output"},
{1,84      ,"Voice Modem Wrapper Line Wave Input"},
{1,85      ,"Voice Modem Wrapper Line Wave Output"},
{1,86      ,"Voice Modem Wrapper Handset Wave Input"},
{1,87      ,"Voice Modem Wrapper Handset Wave Output"},
{1,88      ,"Voice Modem Wrapper Mixer"},
{1,89      ,"Voice Modem Game Compatible Wave Device"},
{1,90      ,"Voice Modem Game Compatible Wave Device"},
{1,91      ,"MM_MSFT_ACM_MSNAUDIO"},
{1,92      ,"MM_MSFT_ACM_MSG723"},
{1,93      ,"MM_MSFT_ACM_MSRT24"},
{1,100     ,"Generic id for WDM Audio drivers"},
{1,101     ,"Generic id for WDM Audio drivers"},
{1,102     ,"Generic id for WDM Audio drivers"},
{1,103     ,"Generic id for WDM Audio drivers"},
{1,104     ,"Generic id for WDM Audio drivers"},
{1,105     ,"Generic id for WDM Audio drivers"}, 

// Creative
{2,1       ,"Sound Blaster 1.5 waveform input"},
{2,2       ,"Sound Blaster 2.0 waveform input"},
{2,3       ,"Sound Blaster Pro waveform input"},
{2,4       ,"Sound Blaster 16 waveform input"},
{2,5       ,"MM_CREATIVE_PHNBLST_WAVEIN"},
{2,101     ,"Sound Blaster 1.5 waveform output"},
{2,102     ,"Sound Blaster 2.0 waveform output"},
{2,103     ,"Sound Blaster Pro waveform output"},
{2,104     ,"Sound Blaster 16 waveform output"},
{2,105     ,"MM_CREATIVE_PHNBLST_WAVEOUT"},
{2,201     ,"Sound Blaster midi out"},
{2,202     ,"Sound Blaster midi in"},
{2,301     ,"Sound Blaster mono synthesizer"},
{2,302     ,"Sound Blaster Pro stereo synthesizer"},
{2,303     ,"MM_CREATIVE_MIDI_AWE32"},
{2,401     ,"Sound Blaster Pro aux (CD)"},
{2,402     ,"Sound Blaster Pro aux (Line in)"},
{2,403     ,"Sound Blaster Pro aux (mic)"},
{2,404     ,"MM_CREATIVE_AUX_MASTER"},
{2,405     ,"MM_CREATIVE_AUX_PCSPK"},
{2,406     ,"MM_CREATIVE_AUX_WAVE"},
{2,407     ,"MM_CREATIVE_AUX_MIDI"},
{2,408     ,"Sound Blaster Pro mixer"},
{2,409     ,"Sound Blaster 16 mixer"},
// Aureal
{181,16    ,"AU8820 (Vortex 1)"},
{181,17    ,"AU8820 synthesizer"},
{181,18    ,"AU8820 waveform output"},
{181,19    ,"AU8820 waveform input"},
{181,20    ,"AU8820 mixer"},
{181,21    ,"AU8820 aux"},
{181,22    ,"AU8820 midi out"},
{181,23    ,"AU8820 midi in"},
{181,32    ,"AU8820 (Vortex 2)"},
{181,33    ,"AU8830 synthesizer"},
{181,34    ,"AU8830 waveform output"},
{181,35    ,"AU8830 waveform input"},
{181,36    ,"AU8830 mixer"},
{181,37    ,"AU8830 aux"},
{181,38    ,"AU8830 midi out"},
{181,39    ,"AU8830 midi in"}
};

char* GetManString(int n)
{
 for (int i = 0;i<sizeof(ManID)/sizeof(MANID);i++)
 {
  if (ManID[i].code == n) return ManID[i].name;
 }
 return "";
}

char* GetProductString(int m, int p)
{
 for (int i = 0;i<sizeof(ProdID)/sizeof(PRODUCTID);i++)
 {
  if (ProdID[i].pcode == p && ProdID[i].mcode == m) return ProdID[i].name;
 }
 return "";
}